const thing = {
  searchResponse: {
    totalResults: '127198',
    time: '0.155724s',
    aggregates: { count: { buckets: {} } },
    aggregateFilters: {
      'count.tags': {
        count: {
          counts: {
            'Scope Of Delivery_No Original Box No Original Papers': 25641,
            'Scope Of Delivery_Original Box No Original Papers': 13668,
            'Scope Of Delivery_Original Box Original Papers': 82733,
            'Scope Of Delivery_Original Papers No Original Box': 3544,
          },
        },
      },
    },
    results: [
      {
        values: {
          _id: { single: '46d48dfb-9291-723e-7acf-49cdd26ec3ec' },
          body_html: {
            single:
              'Product Specifications Basic Info Brand IWC Movement Manual winding Case material Yellow gold Year of production 1947 Scope of delivery No original box, no original papers Weight 5lb Caliber Movement Manual winding Case Case material Yellow gold Dial White Condition Very good (Worn with little to no signs of wear) Scope of delivery No original box, no original papers',
          },
          brandv2: { single: 'Iwc' },
          buysafeLabel: { single: 'Buysafe' },
          caseMaterial: { single: 'Yellow Gold' },
          collection_ids: {
            repeated: {
              values: [
                '180498694275',
                '180580974723',
                '180897972355',
                '180898889859',
                '211921404053',
                '243817283783',
                '285088743623',
                '286056087751',
                '286056120519',
              ],
            },
          },
          collection_titles: {
            repeated: {
              values: [
                'IWC',
                'Master Collection (All Products)',
                'Yellow Gold Watches',
                'Pre-Owned Luxury Watches',
                'All',
                'All',
                'All Products',
                'Best Selling Products',
                'Newest Products',
              ],
            },
          },
          condition: { single: 'Very Good' },
          created_at: { single: '2022-02-27T11:09:41Z' },
          dialColor: { single: 'White' },
          handle: { single: 'iwc-schaffhausen-3' },
          id: { single: '7270955286727' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960', '960', '960'] } },
          image_ids: { repeated: { values: ['33277787635911', '33277787668679', '33277787701447'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/74f317fbebc90be92bbfc401ff6a5ca9.jpg?v=1648213327',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/74f317fbebc90be92bbfc401ff6a5ca9.jpg?v=1648213327',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/7bc33489ffdc91827322fc3fa52ab8b8.jpg?v=1648213327',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/5b720ef7b6f701b7b792d05f326ec4b0.jpg?v=1648213327',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960', '960', '960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '2905.11' },
          min_price: { single: '2905.11' },
          movement: { single: 'Manual Winding' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Pre-Owned Watches' },
          productionYear: { single: '1947' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'No Original Box No Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '1947',
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Brand_Iwc',
                'Case Material_Yellow Gold',
                'Condition_Very Good',
                'Dial Color_White',
                'Iwc',
                'Manual Winding',
                'Movement_Manual Winding',
                'Pre-Owned Luxury Watches',
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e1. \u003c/span\u003eLess than $5K",
                'Reseller_Auktioneum Gmbh',
                'Scope Of Delivery_No Original Box No Original Papers',
                'White',
                'Year Of Production_1947',
                'Yellow Gold',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          title: { single: 'IWC Schaffhausen' },
          updated_at: { single: '2022-07-16T15:00:06Z' },
          variant_compare_at_prices: { repeated: { values: ['3042'] } },
          variant_ids: { repeated: { values: ['41879534829767'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['2905.11'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['IWC775127392'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'IWC' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.12719149745884864,
      },
      {
        values: {
          _id: { single: '6f1c7b2b-b4fd-f1ab-e9ce-e2166cf20061' },
          body_html: {
            single:
              'Product Specifications Basic Info Brand Rolex Model Datejust 36 Movement Automatic Case material Steel Bracelet material Steel Year of production 2022 Scope of delivery Original box, original papers Weight 5lb Caliber Movement Automatic Power reserve 70 h Number of jewels 31 Case Case material Steel Case diameter 36 mm Try it on Water resistance 10 ATM Dial Black Bracelet/strap Bracelet material Steel Clasp Fold clasp Other Chronometer Condition New (Brand new, without any signs of wear) Scope of delivery Original box, original papers',
          },
          braceletMaterial: { single: 'Steel' },
          brandv2: { single: 'Rolex' },
          buysafeLabel: { single: 'Buysafe' },
          caseDiameter: { single: '36 Mm Try It On' },
          caseMaterial: { single: 'Steel' },
          clasp: { single: 'Fold Clasp' },
          collection_ids: { repeated: {} },
          collection_titles: { repeated: {} },
          condition: { single: 'New' },
          created_at: { single: '2022-06-06T16:03:46Z' },
          dialColor: { single: 'Black' },
          handle: { single: 'rolex-datejust-36mm-stainless-steel-126284rbr-black-diamond-oyster' },
          id: { single: '7358706712775' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960'] } },
          image_ids: { repeated: { values: ['34318556397767'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/b1417e592fe6b34fe23f6b694ce7d9de.jpg?v=1654531427',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/b1417e592fe6b34fe23f6b694ce7d9de.jpg?v=1654531427',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '25726.34' },
          min_price: { single: '25726.34' },
          model: { single: 'Datejust 36' },
          movement: { single: 'Automatic' },
          numberOfJewels: { single: '31' },
          option_title: { repeated: { values: ['Default Title'] } },
          powerReserve: { single: '70 H' },
          product_type: { single: 'Diamond Watches' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'Original Box Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '10 Atm',
                '2022',
                '31',
                '36 Mm\nTry It On',
                '70 H',
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Automatic',
                'Black',
                'Bracelet Material_Steel',
                'Brand_Rolex',
                'Case Diameter_36 Mm\nTry It On',
                'Case Material_Steel',
                'Clasp_Fold Clasp',
                'Condition_New',
                'Datejust 36',
                'Dial Color_Black',
                'Diamond Watches',
                'Fold Clasp',
                'Model_Datejust 36',
                'Movement_Automatic',
                'Number Of Jewels_31',
                'Power Reserve_70 H',
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e4. \u003c/span\u003e$25K - $50K",
                'Reseller_None',
                'Rolex',
                'Scope Of Delivery_Original Box Original Papers',
                'Steel',
                'Water Resistance_10 Atm',
                'Year Of Production_2022',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          title: { single: 'Rolex Datejust 36mm Stainless Steel 126284rbr Black Diamond Oyster' },
          updated_at: { single: '2022-06-06T16:03:47Z' },
          variant_compare_at_prices: { repeated: { values: ['26522'] } },
          variant_ids: { repeated: { values: ['42290410127559'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['25726.34'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['ROL362907940'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Rolex' },
          waterResistance: { single: '10 Atm' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 1,
      },
      {
        values: {
          _id: { single: '389e2c8c-8e3e-c8e5-4bc3-020f6d5dd105' },
          body_html: {
            single:
              'Product Specifications Basic Info Brand Seiko Model Grand Seiko Year of production Unknown Scope of delivery Original box, original papers Condition New (Brand new, without any signs of wear) Scope of delivery Original box, original papers',
          },
          brandv2: { single: 'Seiko' },
          buysafeLabel: { single: 'Buysafe' },
          collection_ids: {
            repeated: {
              values: [
                '180510490755',
                '180510589059',
                '180580974723',
                '180898267267',
                '211921404053',
                '243817283783',
                '285088743623',
                '286056087751',
                '286056120519',
              ],
            },
          },
          collection_titles: {
            repeated: {
              values: [
                'Seiko',
                'Seiko Grand Seiko',
                'Master Collection (All Products)',
                'Manual Winding Watches',
                'All',
                'All',
                'All Products',
                'Best Selling Products',
                'Newest Products',
              ],
            },
          },
          condition: { single: 'New' },
          created_at: { single: '2022-02-26T00:06:55Z' },
          handle: { single: 'seiko-grand-seiko-elegance-collection-hand-wind-sbgk007-watch' },
          id: { single: '7268726800583' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960'] } },
          image_ids: { repeated: { values: ['33261719879879'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/1f474aac2881bf0ba808638ef949df1c.jpg?v=1648210806',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/1f474aac2881bf0ba808638ef949df1c.jpg?v=1648210806',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '4866.68' },
          min_price: { single: '4866.68' },
          model: { single: 'Grand Seiko' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Watch' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'Original Box Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Brand_Seiko',
                'Condition_New',
                'Grand Seiko',
                'Manual Winding Watches',
                'Model_Grand Seiko',
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e2. \u003c/span\u003e$5K - $10K",
                'Reseller_Ippo Japan Watch',
                'Scope Of Delivery_Original Box Original Papers',
                'Seiko',
                'Unknown',
                'Year Of Production_Unknown',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          title: { single: 'Seiko Grand Seiko Elegance Collection Hand-wind SBGK007 Watch' },
          updated_at: { single: '2022-06-13T00:27:44Z' },
          variant_compare_at_prices: { repeated: { values: ['5096'] } },
          variant_ids: { repeated: { values: ['41873152966855'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['4866.68'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['SEI425304459'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Seiko' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.06837558969336098,
      },
      {
        values: {
          _id: { single: '33a4eb8f-960f-90ff-b3df-8044418bf0d4' },
          body_html: {
            single:
              "Product Specifications Basic Info Movement Automatic Case material Bracelet material Year of production 2021 Scope of delivery original box, original papers Gender Men's watch/Unisex Weight 5lb Caliber Movement Automatic Case Case material Case diameter 40 mm Dial Bracelet/strap Bracelet material Functions Year 2021 Condition Very good Scope of delivery original box, original papers",
          },
          brandv2: { single: 'Rolex' },
          collection_ids: {
            repeated: {
              values: [
                '180580974723',
                '211921404053',
                '243817283783',
                '261361434823',
                '272281239751',
                '284589654215',
                '285088743623',
                '285255565511',
                '285464232135',
                '285780148423',
                '286056087751',
                '286056120519',
              ],
            },
          },
          collection_titles: {
            repeated: {
              values: [
                'Master Collection (All Products)',
                'All',
                'All',
                'Recommended',
                'Highly Recommended',
                'Gift Cards',
                'All Products',
                'Girard-Perregaux',
                'Auctions',
                'Rolex',
                'Best Selling Products',
                'Newest Products',
              ],
            },
          },
          created_at: { single: '2022-04-20T05:04:20Z' },
          handle: { single: 'rolex-day-date-40mm-228348rbr' },
          id: { single: '7323174535367' },
          image_height: { single: '4032' },
          image_heights: { repeated: { values: ['4032', '4032'] } },
          image_ids: { repeated: { values: ['33844146831559', '33844146864327'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/5FA03ABF-1E87-4C01-BCC7-B8FCBC993A39.jpg?v=1650714243',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/5FA03ABF-1E87-4C01-BCC7-B8FCBC993A39.jpg?v=1650714243',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/4BD2AA48-255E-4C26-94FC-B98978DA4E3C.jpg?v=1650714243',
              ],
            },
          },
          image_width: { single: '3024' },
          image_widths: { repeated: { values: ['3024', '3024'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '75000' },
          min_price: { single: '75000' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Wristwatch' },
          published_at: { single: '2022-04-20T05:04:22Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: ['228348RBR', 'Brand_Rolex', 'rolex', 'Rolex Day-Date', 'Rolex Day-Date 40mm  228348RBR'],
            },
          },
          template_suffix: { single: '' },
          title: { single: 'Rolex Day-Date 40mm  228348RBR' },
          updated_at: { single: '2022-06-08T21:34:13Z' },
          variant_compare_at_prices: { repeated: { values: ['0'] } },
          variant_ids: { repeated: { values: ['42114707849415'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['75000'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: [''] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Rolex' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.06837558969336098,
      },
      {
        values: {
          _id: { single: '77ddb7c2-f9ed-5304-27ba-85068b7c9b68' },
          body_html: {
            single:
              "Product Specifications Basic Info Brand Rolex Model Datejust 36 Bracelet material Steel Year of production Unknown Scope of delivery Original box, no original papers Gender Men's watch/Unisex Weight 5lb Bracelet/strap Bracelet material Steel Bracelet color Steel Functions Date Other Quick Set Condition Very good (Worn with little to no signs of wear) Scope of delivery Original box, no original papers",
          },
          braceletMaterial: { single: 'Steel' },
          bracelet_color: { single: 'Steel' },
          brandv2: { single: 'Rolex' },
          buysafeLabel: { single: 'Buysafe' },
          collection_ids: {
            repeated: {
              values: [
                '180370866307',
                '180580974723',
                '180899577987',
                '181399683203',
                '211921404053',
                '243817283783',
                '285088743623',
                '285780148423',
                '286056087751',
                '286056120519',
              ],
            },
          },
          collection_titles: {
            repeated: {
              values: [
                "Men's Watches",
                'Master Collection (All Products)',
                'Swiss watch manufacturers',
                "Men's Watches 5K - 10K",
                'All',
                'All',
                'All Products',
                'Rolex',
                'Best Selling Products',
                'Newest Products',
              ],
            },
          },
          condition: { single: 'Very Good' },
          created_at: { single: '2022-05-05T19:48:34Z' },
          gender: { single: "Men's Watch/Unisex" },
          handle: { single: 'rolex-mens-rolex-datejust-watch-16220-stainless-steel-blue-dial-1' },
          id: { single: '7335636304071' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960'] } },
          image_ids: { repeated: { values: ['34030876786887'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/10d898715783876ff55413332ba982f6.jpg?v=1651925676',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/10d898715783876ff55413332ba982f6.jpg?v=1651925676',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '6590.46' },
          min_price: { single: '6590.46' },
          model: { single: 'Datejust 36' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Watch' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'Original Box No Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Bracelet Color_Steel',
                'Bracelet Material_Steel',
                'Brand_Rolex',
                'Condition_Very Good',
                'Date',
                'Datejust 36',
                "Gender_Men's Watch/Unisex",
                "Men's Watch/Unisex",
                'Model_Datejust 36',
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e2. \u003c/span\u003e$5K - $10K",
                'Reseller_Demesy Fine Watches',
                'Rolex',
                'Scope Of Delivery_Original Box No Original Papers',
                'Steel',
                'Swiss watch manufacturers',
                'Unknown',
                'Year Of Production_Unknown',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          title: { single: "Rolex Men's Rolex Datejust Watch 16220 Stainless Steel  Blue Dial" },
          updated_at: { single: '2022-06-02T13:58:53Z' },
          variant_compare_at_prices: { repeated: { values: ['6901'] } },
          variant_ids: { repeated: { values: ['42170982531271'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['6590.46'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['ROL104008437'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Rolex' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.06506153899696113,
      },
      {
        values: {
          _id: { single: 'd399425f-3231-899c-f0bf-0c8c744ddb83' },
          body_html: {
            single:
              "Product Specifications Basic Info Brand Rolex Model Datejust 31 Case material Steel Bracelet material Steel Year of production Unknown Scope of delivery No original box, no original papers Gender Men's watch/Unisex Weight 5lb Case Case material Steel Bracelet/strap Bracelet material Steel Bracelet color Steel Functions Date Other Quick Set Condition Very good (Worn with little to no signs of wear) Scope of delivery No original box, no original papers",
          },
          braceletMaterial: { single: 'Steel' },
          bracelet_color: { single: 'Steel' },
          brandv2: { single: 'Rolex' },
          buysafeLabel: { single: 'Buysafe' },
          caseMaterial: { single: 'Steel' },
          collection_ids: {
            repeated: {
              values: [
                '180370866307',
                '180580974723',
                '180899577987',
                '181399683203',
                '211921404053',
                '243817283783',
                '285088743623',
                '285780148423',
                '286056087751',
                '286056120519',
              ],
            },
          },
          collection_titles: {
            repeated: {
              values: [
                "Men's Watches",
                'Master Collection (All Products)',
                'Swiss watch manufacturers',
                "Men's Watches 5K - 10K",
                'All',
                'All',
                'All Products',
                'Rolex',
                'Best Selling Products',
                'Newest Products',
              ],
            },
          },
          condition: { single: 'Very Good' },
          created_at: { single: '2022-06-06T15:55:31Z' },
          gender: { single: "Men's Watch/Unisex" },
          handle: { single: 'rolex-datejust-midsize-mens-or-ladies-steel-watch-178243' },
          id: { single: '7358700290247' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960'] } },
          image_ids: { repeated: { values: ['34318441971911'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/4283d46dbb0a5c896ffcb8fe3bc6b50e.jpg?v=1654948366',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/4283d46dbb0a5c896ffcb8fe3bc6b50e.jpg?v=1654948366',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '6541.75' },
          min_price: { single: '6541.75' },
          model: { single: 'Datejust 31' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Watch' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'No Original Box No Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Bracelet Color_Steel',
                'Bracelet Material_Steel',
                'Brand_Rolex',
                'Case Material_Steel',
                'Condition_Very Good',
                'Date',
                'Datejust 31',
                "Gender_Men's Watch/Unisex",
                "Men's Watch/Unisex",
                'Model_Datejust 31',
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e2. \u003c/span\u003e$5K - $10K",
                'Reseller_None',
                'Rolex',
                'Scope Of Delivery_No Original Box No Original Papers',
                'Steel',
                'Swiss watch manufacturers',
                'Unknown',
                'Year Of Production_Unknown',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          title: { single: "Rolex Datejust Midsize Men's or Ladies Steel Watch 178240" },
          updated_at: { single: '2022-06-11T11:52:46Z' },
          variant_compare_at_prices: { repeated: { values: ['6850'] } },
          variant_ids: { repeated: { values: ['42290393317575'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['6541.75'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['ROL608272558'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Rolex' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.3890954464023764,
      },
      {
        values: {
          _id: { single: '1c63a57a-a02b-ee94-37cf-f8abc479b54b' },
          body_html: {
            single:
              'Product Specifications Basic Info Brand Rolex Model Explorer Year of production 2020 Scope of delivery Original box, original papers Weight 5lb Case Case diameter 39 mm Try it on Scope of delivery Original box, original papers',
          },
          brandv2: { single: 'Rolex' },
          buysafeLabel: { single: 'Buysafe' },
          caseDiameter: { single: '39 Mm Try It On' },
          collection_ids: {
            repeated: {
              values: [
                '180181336195',
                '180580974723',
                '180900298883',
                '211921404053',
                '243817283783',
                '285088743623',
                '285780148423',
                '286056087751',
                '286056120519',
              ],
            },
          },
          collection_titles: {
            repeated: {
              values: [
                'Rolex EXPLORER',
                'Master Collection (All Products)',
                'Waterproof Watches',
                'All',
                'All',
                'All Products',
                'Rolex',
                'Best Selling Products',
                'Newest Products',
              ],
            },
          },
          created_at: { single: '2022-07-12T16:40:27Z' },
          handle: { single: 'rolex-explorer-1-ref-214270-39mm-mkii-dial-last-generation' },
          id: { single: '7398559285447' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960', '960', '960'] } },
          image_ids: { repeated: { values: ['34769528291527', '34769528324295', '34769528357063'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/6432bd76704a31891ed626f821a5c7b4.jpg?v=1657644027',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/6432bd76704a31891ed626f821a5c7b4.jpg?v=1657644027',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/f74805c40676a8b0c5419c7549fd7b33.jpg?v=1657644027',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/3c13b99d2edaf7deca63c8741d7e0de7.jpg?v=1657644027',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960', '960', '960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '10481.13' },
          min_price: { single: '10481.13' },
          model: { single: 'Explorer' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Watch' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'Original Box Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '2020',
                '39 Mm\nTry It On',
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Brand_Rolex',
                'Case Diameter_39 Mm\nTry It On',
                'Explorer',
                'Model_Explorer',
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e3. \u003c/span\u003e$10 - $25K",
                'Reseller_None',
                'Rolex',
                'Scope Of Delivery_Original Box Original Papers',
                'Waterproof Watches',
                'Year Of Production_2020',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          title: { single: 'Rolex Explorer 1 Ref 214270 39mm MKII Dial Last Generation' },
          updated_at: { single: '2022-07-12T16:40:30Z' },
          variant_compare_at_prices: { repeated: { values: ['10975'] } },
          variant_ids: { repeated: { values: ['42444405113031'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['10481.13'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['ROL416203419'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Rolex' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.3890954464023764,
      },
      {
        values: {
          _id: { single: 'f407783a-dc5a-751c-1e2c-be2363635a74' },
          body_html: {
            single:
              "Product Specifications Basic Info Brand IWC Movement Automatic Year of production 2022 Scope of delivery Original box, original papers Gender Men's watch/Unisex Weight 5lb Caliber Movement Automatic Case Case diameter 41 mm Try it on Condition New (Brand new, without any signs of wear) Scope of delivery Original box, original papers",
          },
          brandv2: { single: 'Iwc' },
          buysafeLabel: { single: 'Buysafe' },
          caseDiameter: { single: '41 Mm Try It On' },
          collection_ids: { repeated: {} },
          collection_titles: { repeated: {} },
          condition: { single: 'New' },
          created_at: { single: '2022-07-18T09:58:09Z' },
          gender: { single: "Men's Watch/Unisex" },
          handle: { single: 'iwc-pilot-chronograph-41-edition-mercedes-amg-petronas-formula-one-team-1' },
          id: { single: '7409409163463' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960', '960', '960'] } },
          image_ids: { repeated: { values: ['34875318272199', '34875318304967', '34875318337735'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/3cf900f836b63417c211159e8fe04fd2.jpg?v=1658138289',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/3cf900f836b63417c211159e8fe04fd2.jpg?v=1658138289',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/b82f631e4b648cbb7f164638a323f3a4.jpg?v=1658138289',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/8864cd6d65579104451d0064ffce1e47.jpg?v=1658138289',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960', '960', '960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '10982.5' },
          min_price: { single: '10982.5' },
          movement: { single: 'Automatic' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Watch' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'Original Box Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '2022',
                '41 Mm\nTry It On',
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Automatic',
                'Brand_Iwc',
                'Case Diameter_41 Mm\nTry It On',
                'Condition_New',
                "Gender_Men's Watch/Unisex",
                'Iwc',
                "Men's Watch/Unisex",
                'Movement_Automatic',
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e3. \u003c/span\u003e$10 - $25K",
                'Reseller_None',
                'Scope Of Delivery_Original Box Original Papers',
                'Swiss watch manufacturers',
                'Year Of Production_2022',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          title: { single: 'IWC Pilot Chronograph 41 Edition Mercedes-AMG Petronas Formula One Team' },
          updated_at: { single: '2022-07-18T09:58:10Z' },
          variant_compare_at_prices: { repeated: { values: ['11500'] } },
          variant_ids: { repeated: { values: ['42469146558663'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['10982.5'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['IWC49928675'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'IWC' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.3584704464023764,
      },
      {
        values: {
          _id: { single: 'df5c2a71-02b4-cb52-f330-d784574de01c' },
          body_html: {
            single:
              'Product Specifications Basic Info Brand Patek Philippe Model Gondolo Movement Manual winding Case material White gold Year of production Unknown Scope of delivery Original box, no original papers Weight 5lb Caliber Movement Manual winding Case Case material White gold Dial Blue Condition Very good (Worn with little to no signs of wear) Scope of delivery Original box, no original papers',
          },
          brandv2: { single: 'Patek Philippe' },
          buysafeLabel: { single: 'Buysafe' },
          caseMaterial: { single: 'White Gold' },
          collection_ids: {
            repeated: {
              values: [
                '180507213955',
                '180580974723',
                '180898922627',
                '181406138499',
                '211921404053',
                '243817283783',
                '285088743623',
                '286056087751',
                '286056120519',
              ],
            },
          },
          collection_titles: {
            repeated: {
              values: [
                'Patek Philippe',
                'Master Collection (All Products)',
                "Pre-Owned Mens' Watches",
                'White Gold Watches',
                'All',
                'All',
                'All Products',
                'Best Selling Products',
                'Newest Products',
              ],
            },
          },
          condition: { single: 'Very Good' },
          created_at: { single: '2022-02-23T18:24:27Z' },
          dialColor: { single: 'Blue' },
          handle: { single: 'patek-philippe-power-reserve' },
          id: { single: '7265024639175' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960'] } },
          image_ids: { repeated: { values: ['33235831849159'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/1b489af5c4feb0502ce9522c51179f54.jpg?v=1647690672',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/1b489af5c4feb0502ce9522c51179f54.jpg?v=1647690672',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '48922.92' },
          min_price: { single: '48922.92' },
          model: { single: 'Gondolo' },
          movement: { single: 'Manual Winding' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Pre-Owned Watches' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'Original Box No Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Blue',
                'Brand_Patek Philippe',
                'Case Material_White Gold',
                'Condition_Very Good',
                'Dial Color_Blue',
                'Gondolo',
                'Manual Winding',
                'Model_Gondolo',
                'Movement_Manual Winding',
                'Patek Philippe',
                "Pre-Owned Mens' Watches",
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e4. \u003c/span\u003e$25K - $50K",
                'Reseller_A.C.Watches',
                'Scope Of Delivery_Original Box No Original Papers',
                'Unknown',
                'White Gold',
                'Year Of Production_Unknown',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          title: { single: 'Patek Philippe Power Reserve' },
          updated_at: { single: '2022-07-13T08:20:43Z' },
          variant_compare_at_prices: { repeated: { values: ['50436'] } },
          variant_ids: { repeated: { values: ['41860872175815'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['48922.92'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['PAT69063011'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Patek Philippe' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.3584704464023764,
      },
      {
        values: {
          _id: { single: 'd24d72a1-36c9-6f1a-b904-44fb51b415bd' },
          body_html: {
            single:
              "Product Specifications Basic Info Brand Omega Model Constellation Movement Automatic Case material White gold Bracelet material White gold Year of production Unknown Scope of delivery Original box, original papers Gender Women's watch Weight 5lb Caliber Movement Automatic Case Case material White gold Case diameter 31 mm Try it on Thickness 12 mm Bracelet/strap Bracelet material White gold Condition Unworn (Mint condition, without signs of wear) Scope of delivery Original box, original papers",
          },
          braceletMaterial: { single: 'White Gold' },
          brandv2: { single: 'Omega' },
          buysafeLabel: { single: 'Buysafe' },
          caseDiameter: { single: '31 Mm Try It On' },
          caseMaterial: { single: 'White Gold' },
          collection_ids: {
            repeated: {
              values: [
                '180505575555',
                '180580974723',
                '180897185923',
                '180900429955',
                '181403844739',
                '181403943043',
                '181406138499',
                '211921404053',
                '243817283783',
                '284886925511',
                '285088743623',
                '286056087751',
                '286056120519',
              ],
            },
          },
          collection_titles: {
            repeated: {
              values: [
                'Omega',
                'Master Collection (All Products)',
                'Automatic Watches',
                "Women's Watches",
                "Women's Watches \u003e 10K",
                "Women's Diamond Watches",
                'White Gold Watches',
                'All',
                'All',
                'Mechanical Watches',
                'All Products',
                'Best Selling Products',
                'Newest Products',
              ],
            },
          },
          condition: { single: 'Unworn' },
          created_at: { single: '2022-05-05T09:24:02Z' },
          gender: { single: "Women's Watch" },
          handle: { single: 'omega-constellation-silver-diamond-white-gold-ladies-watch-123-55-31-20-55-003' },
          id: { single: '7335178895559' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960', '960', '960'] } },
          image_ids: { repeated: { values: ['34026054418631', '34026054451399', '34026054484167'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/e7ea4d86cb31d5fee0940f254e480f0f.jpg?v=1651742642',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/e7ea4d86cb31d5fee0940f254e480f0f.jpg?v=1651742642',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/36bb091d43641b4dccc710fbc75931a6.jpg?v=1651742642',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/77d18860858fceec72642de933775a64.jpg?v=1651742642',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960', '960', '960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '22309.03' },
          min_price: { single: '22309.03' },
          model: { single: 'Constellation' },
          movement: { single: 'Automatic' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Gold Watches' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'Original Box Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '12 Mm',
                '31 Mm\nTry It On',
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Automatic',
                'Bracelet Material_White Gold',
                'Brand_Omega',
                'Case Diameter_31 Mm\nTry It On',
                'Case Material_White Gold',
                'Condition_Unworn',
                'Constellation',
                "Gender_Women's Watch",
                'Gold Watches',
                'Model_Constellation',
                'Movement_Automatic',
                'Omega',
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e3. \u003c/span\u003e$10 - $25K",
                'Reseller_Chronostore',
                'Scope Of Delivery_Original Box Original Papers',
                'Thickness_12 Mm',
                'Unknown',
                'White Gold',
                "Women's Watch",
                'Year Of Production_Unknown',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          thickness: { single: '12 Mm' },
          title: { single: 'Omega Constellation Silver Diamond White Gold Ladies Watch 123.55.31.20.55.003' },
          updated_at: { single: '2022-05-05T09:24:02Z' },
          variant_compare_at_prices: { repeated: { values: ['22999'] } },
          variant_ids: { repeated: { values: ['42169228951751'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['22309.03'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['OME32485088'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Omega' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.3584704464023764,
      },
      {
        values: {
          _id: { single: 'a146b966-9753-3e9f-fd45-05093fb1b8e7' },
          body_html: {
            single:
              "Product Specifications Basic Info Brand Hublot Model Classic Fusion Chronograph Movement Automatic Case material Rose gold Bracelet material Rubber Year of production 2021 Scope of delivery Original box, original papers Gender Men's watch/Unisex Weight 5lb Caliber Movement Automatic Case Case material Rose gold Dial Grey Bracelet/strap Bracelet material Rubber Condition New (Brand new, without any signs of wear) Scope of delivery Original box, original papers",
          },
          braceletMaterial: { single: 'Rubber' },
          brandv2: { single: 'Hublot' },
          buysafeLabel: { single: 'Buysafe' },
          caseMaterial: { single: 'Rose Gold' },
          collection_ids: {
            repeated: {
              values: [
                '180370866307',
                '180497907843',
                '180580974723',
                '180897185923',
                '180898562179',
                '180899217539',
                '181399847043',
                '211921404053',
                '243817283783',
                '284886925511',
                '285088743623',
                '286056087751',
                '286056120519',
              ],
            },
          },
          collection_titles: {
            repeated: {
              values: [
                "Men's Watches",
                'Hublot',
                'Master Collection (All Products)',
                'Automatic Watches',
                'New Watches',
                'Rose Gold Watches',
                "Men's Watches \u003e 10K",
                'All',
                'All',
                'Mechanical Watches',
                'All Products',
                'Best Selling Products',
                'Newest Products',
              ],
            },
          },
          condition: { single: 'New' },
          created_at: { single: '2022-02-21T22:39:42Z' },
          dialColor: { single: 'Grey' },
          gender: { single: "Men's Watch/Unisex" },
          handle: { single: 'hublot-classic-fusion-427' },
          id: { single: '7261599006919' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960'] } },
          image_ids: { repeated: { values: ['33211293565127'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/a21337240421d06e5b53d8b805e28ed8.jpg?v=1647332493',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/a21337240421d06e5b53d8b805e28ed8.jpg?v=1647332493',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '21569.89' },
          min_price: { single: '21569.89' },
          model: { single: 'Classic Fusion Chronograph' },
          movement: { single: 'Automatic' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Watch' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'Original Box Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '2021',
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Automatic',
                'Bracelet Material_Rubber',
                'Brand_Hublot',
                'Case Material_Rose Gold',
                'Classic Fusion Chronograph',
                'Condition_New',
                'Dial Color_Grey',
                "Gender_Men's Watch/Unisex",
                'Grey',
                'Hublot',
                "Men's Watch/Unisex",
                'Model_Classic Fusion Chronograph',
                'Movement_Automatic',
                'New Watches',
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e4. \u003c/span\u003e$25K - $50K",
                'Reseller_Watch Philosophy',
                'Rose Gold',
                'Rubber',
                'Scope Of Delivery_Original Box Original Papers',
                'Year Of Production_2021',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          title: { single: 'Hublot Classic Fusion' },
          updated_at: { single: '2022-07-16T11:40:22Z' },
          variant_compare_at_prices: { repeated: { values: ['22237'] } },
          variant_ids: { repeated: { values: ['41848752603335'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['21569.89'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['HUB168010930'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Hublot' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.06837558969336098,
      },
      {
        values: {
          _id: { single: '173bb5b0-ddd7-194a-7517-a22850585837' },
          body_html: {
            single:
              'Product Specifications Basic Info Brand Seiko Model Grand Seiko Year of production 2019 Scope of delivery Original box, original papers Condition Very good (Worn with little to no signs of wear) Scope of delivery Original box, original papers',
          },
          brandv2: { single: 'Seiko' },
          buysafeLabel: { single: 'Buysafe' },
          collection_ids: {
            repeated: {
              values: [
                '180510490755',
                '180510589059',
                '180580974723',
                '180897906819',
                '211921404053',
                '243817283783',
                '285088743623',
                '286056087751',
                '286056120519',
              ],
            },
          },
          collection_titles: {
            repeated: {
              values: [
                'Seiko',
                'Seiko Grand Seiko',
                'Master Collection (All Products)',
                'GMT Watches',
                'All',
                'All',
                'All Products',
                'Best Selling Products',
                'Newest Products',
              ],
            },
          },
          condition: { single: 'Very Good' },
          created_at: { single: '2022-05-06T08:36:49Z' },
          handle: { single: 'seiko-grant-seiko-hi-beat-gmt-titanium-sbgj211-1' },
          id: { single: '7336314110151' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960'] } },
          image_ids: { repeated: { values: ['34038084370631'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/670e13114bc15c4498d112d0f6bc6a1a.jpg?v=1651826210',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/670e13114bc15c4498d112d0f6bc6a1a.jpg?v=1651826210',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '7067' },
          min_price: { single: '7067' },
          model: { single: 'Grand Seiko' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Watch' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'Original Box Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '2019',
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Brand_Seiko',
                'Condition_Very Good',
                'GMT Watches',
                'Grand Seiko',
                'Model_Grand Seiko',
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e2. \u003c/span\u003e$5K - $10K",
                'Reseller_Watch Awristocrat',
                'Scope Of Delivery_Original Box Original Papers',
                'Seiko',
                'Year Of Production_2019',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          title: { single: 'Seiko Grant Seiko Hi-Beat GMT Titanium SBGJ211' },
          updated_at: { single: '2022-05-06T08:36:50Z' },
          variant_compare_at_prices: { repeated: { values: ['7400'] } },
          variant_ids: { repeated: { values: ['42174764056775'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['7067'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['SEI313696865'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Seiko' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.3890954464023764,
      },
      {
        values: {
          _id: { single: 'cb4f5df2-bdae-2aac-33d9-d60818f87fbb' },
          body_html: {
            single:
              'Product Specifications Basic Info Movement Quartz Case material Yellow gold Year of production Unknown Scope of delivery No original box, no original papers Weight 5lb Caliber Movement Quartz Case Case material Yellow gold Case diameter 25 x 29 mm Try it on Thickness 5 mm Dial Gold Bracelet/strap Bracelet color Gold Bracelet length 191 mm Condition Good (Light signs of wear or scratches) Scope of delivery No original box, no original papers',
          },
          braceletLength: { single: '191 Mm' },
          bracelet_color: { single: 'Gold' },
          buysafeLabel: { single: 'Buysafe' },
          caseDiameter: { single: '25 X 29 Mm Try It On' },
          caseMaterial: { single: 'Yellow Gold' },
          collection_ids: { repeated: {} },
          collection_titles: { repeated: {} },
          condition: { single: 'Good' },
          created_at: { single: '2022-06-06T15:36:32Z' },
          dialColor: { single: 'Gold' },
          handle: { single: 'geneve-geneve-14k-yellow-gold-with-diamonds-watch' },
          id: { single: '7358675419335' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960', '960', '960'] } },
          image_ids: { repeated: { values: ['34318311751879', '34318311784647', '34318311817415'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/a4969bfece89340ed8672561faaedb52.jpg?v=1654529792',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/a4969bfece89340ed8672561faaedb52.jpg?v=1654529792',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/647f6db0d2c4dd2916f67c496a8751a4.jpg?v=1654529792',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/f48d0f1dc6c8bf431cd36708b504c60b.jpg?v=1654529792',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960', '960', '960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '3724.5' },
          min_price: { single: '3724.5' },
          movement: { single: 'Quartz' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Watch' },
          productionYear: { single: 'Unknown' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'No Original Box No Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '191 Mm',
                '25 X 29 Mm\nTry It On',
                '5 Mm',
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Bracelet Color_Gold',
                'Bracelet Length_191 Mm',
                'Case Diameter_25 X 29 Mm\nTry It On',
                'Case Material_Yellow Gold',
                'Condition_Good',
                'Dial Color_Gold',
                'Gold',
                'Movement_Quartz',
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e1. \u003c/span\u003eLess than $5K",
                'Quartz',
                'Quartz Watches',
                'Reseller_None',
                'Scope Of Delivery_No Original Box No Original Papers',
                'Thickness_5 Mm',
                'Unknown',
                'Year Of Production_Unknown',
                'Yellow Gold',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          thickness: { single: '5 Mm' },
          title: { single: 'Geneve Genève 14K Yellow Gold with Diamonds WATCH' },
          updated_at: { single: '2022-06-06T15:36:35Z' },
          variant_compare_at_prices: { repeated: { values: ['3900'] } },
          variant_ids: { repeated: { values: ['42290334269639'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['3724.5'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['439757014'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Watch Rapport' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.034558745852546154,
      },
      {
        values: {
          _id: { single: 'eac9be8c-978d-c83d-4eeb-977a9ffc4386' },
          body_html: {
            single:
              "Product Specifications Purchased from the original owner approx 8 years ago… never personally worn.. very sharp look! Basic Info Movement Automatic Case material Stainless Steel Bracelet material Stainless Steel Year of production 2005 Scope of delivery original box, original papers Gender Men's watch/Unisex Weight 5lb Caliber Calibre 2892A2 Movement Automatic Case Case material Case diameter 48 mm Dial Bracelet/strap Bracelet material Functions Year 2005 Condition Very good Scope of delivery original box, original papers",
          },
          braceletMaterial: { single: 'Steel' },
          brandv2: { single: 'Franck Muller' },
          caseDiameter: { single: '48 Mm' },
          caseMaterial: { single: 'Steel' },
          collection_ids: {
            repeated: {
              values: [
                '180495155331',
                '180580974723',
                '211921404053',
                '243817283783',
                '285088743623',
                '286056087751',
                '286056120519',
              ],
            },
          },
          collection_titles: {
            repeated: {
              values: [
                'Franck Muller',
                'Master Collection (All Products)',
                'All',
                'All',
                'All Products',
                'Best Selling Products',
                'Newest Products',
              ],
            },
          },
          created_at: { single: '2022-05-04T05:10:44Z' },
          handle: { single: 'franck-muller-conquistador-8002-sc-48mm' },
          id: { single: '7333994070215' },
          image_height: { single: '3765' },
          image_heights: { repeated: { values: ['3765', '4032', '4032', '1909', '4032', '2236', '4032', '1785'] } },
          image_ids: {
            repeated: {
              values: [
                '34011410432199',
                '34011410268359',
                '34011410694343',
                '34011410235591',
                '34011410759879',
                '34011410661575',
                '34011410727111',
                '34011410301127',
              ],
            },
          },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/23FE76A3-3DEA-474E-A18A-B4AA6739C0D2.jpg?v=1651641047',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/23FE76A3-3DEA-474E-A18A-B4AA6739C0D2.jpg?v=1651641047',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/44D1D965-AB1A-4040-968B-5EF92AF5D015.jpg?v=1651641047',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/4490837E-EEC0-44F2-A4E9-FC76FAA743F8.jpg?v=1651641047',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/6840923E-2847-46AD-9707-31FB6BA9A028.jpg?v=1651641047',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/DA4F4958-EE16-4EEE-8FD2-EF78C71656BC.jpg?v=1651641048',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/F67B8EFB-4A4A-4037-AD5F-647724772F41.jpg?v=1651641048',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/56F38971-8266-4716-BF8C-F7C052EC7C41.jpg?v=1651641048',
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/51330953-EC98-454A-AB03-960E4BB25FE2.jpg?v=1651641048',
              ],
            },
          },
          image_width: { single: '2437' },
          image_widths: { repeated: { values: ['2437', '3024', '3024', '1420', '3024', '2981', '3024', '1483'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '17700' },
          min_price: { single: '17700' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Wristwatch' },
          published_at: { single: '2022-05-04T05:10:46Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                'Bracelet Material_Steel',
                'Brand_Franck Muller',
                'Case Diameter_48 Mm',
                'Case Material_Steel',
                'Franck Muller',
              ],
            },
          },
          template_suffix: { single: '' },
          title: { single: 'Franck Muller Conquistador # 8002 SC 48mm' },
          updated_at: { single: '2022-05-04T05:15:20Z' },
          variant_compare_at_prices: { repeated: { values: ['0'] } },
          variant_ids: { repeated: { values: ['42165006893255'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['17700'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: [''] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Franck Muller' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.06837558969336098,
      },
      {
        values: {
          _id: { single: '710058c1-cef1-0765-7ec0-ae0c4228efce' },
          body_html: {
            single:
              'Product Specifications Basic Info Brand Glashütte Original Model Senator Cosmopolite Movement Manual winding Case material White gold Bracelet material Leather Year of production 2021 Scope of delivery Original box, original papers Weight 5lb Caliber Movement Manual winding Case Case material White gold Case diameter 44 mm Dial Silver Bracelet/strap Bracelet material Leather Condition Unworn (Mint condition, without signs of wear) Scope of delivery Original box, original papers',
          },
          braceletMaterial: { single: 'Leather' },
          brandv2: { single: 'Glashütte Original' },
          buysafeLabel: { single: 'Buysafe' },
          caseDiameter: { single: '44 Mm' },
          caseMaterial: { single: 'White Gold' },
          collection_ids: {
            repeated: {
              values: [
                '180495974531',
                '180580974723',
                '180898562179',
                '181406138499',
                '211921404053',
                '243817283783',
                '285088743623',
                '286056087751',
                '286056120519',
              ],
            },
          },
          collection_titles: {
            repeated: {
              values: [
                'Glashütte Original',
                'Master Collection (All Products)',
                'New Watches',
                'White Gold Watches',
                'All',
                'All',
                'All Products',
                'Best Selling Products',
                'Newest Products',
              ],
            },
          },
          condition: { single: 'Unworn' },
          created_at: { single: '2022-02-22T00:34:26Z' },
          dialColor: { single: 'Silver' },
          handle: { single: 'glashutte-original-cosmopolite-1-89-02-01-04-01' },
          id: { single: '7261781491911' },
          image_height: { single: '960' },
          image_heights: { repeated: { values: ['960'] } },
          image_ids: { repeated: { values: ['33212378677447'] } },
          image_tags: { repeated: {} },
          image_url: {
            single:
              'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/41552d8b700536645e5473212a4eb3a9.jpg?v=1647681082',
          },
          image_urls: {
            repeated: {
              values: [
                'https://cdn.shopify.com/s/files/1/0355/9843/4435/products/41552d8b700536645e5473212a4eb3a9.jpg?v=1647681082',
              ],
            },
          },
          image_width: { single: '960' },
          image_widths: { repeated: { values: ['960'] } },
          inventory_quantity: { single: '1' },
          max_price: { single: '27058.15' },
          min_price: { single: '27058.15' },
          model: { single: 'Senator Cosmopolite' },
          movement: { single: 'Manual Winding' },
          option_title: { repeated: { values: ['Default Title'] } },
          product_type: { single: 'Watch' },
          published_at: { single: '2022-01-22T05:03:00Z' },
          published_scope: { single: 'web' },
          requires_shipping: { single: 'true' },
          scopeofdelivery: { single: 'Original Box Original Papers' },
          status: { single: 'active' },
          tags: {
            repeated: {
              values: [
                '2021',
                '44 Mm',
                '__label1:Tax Free',
                '__label2:Buysafe',
                'Bracelet Material_Leather',
                'Brand_Glashütte Original',
                'Case Diameter_44 Mm',
                'Case Material_White Gold',
                'Condition_Unworn',
                'Dial Color_Silver',
                'Glashütte Original',
                'Leather',
                'Manual Winding',
                'Model_Senator Cosmopolite',
                'Movement_Manual Winding',
                'New Watches',
                "Price Range_\u003cspan style='text-color:white;color:white'\u003e4. \u003c/span\u003e$25K - $50K",
                'Reseller_Uhrentrader W.C Gmbh',
                'Scope Of Delivery_Original Box Original Papers',
                'Senator Cosmopolite',
                'Silver',
                'White Gold',
                'Year Of Production_2021',
              ],
            },
          },
          taxfreeLabel: { single: 'Tax Free' },
          template_suffix: { single: '' },
          title: { single: 'Glashütte Original Cosmopolite 1-89-02-01-04-01' },
          updated_at: { single: '2022-07-18T21:07:45Z' },
          variant_compare_at_prices: { repeated: { values: ['27895'] } },
          variant_ids: { repeated: { values: ['41849194676423'] } },
          variant_image_ids: { repeated: { values: ['0'] } },
          variant_options_1: { repeated: { values: ['Default Title'] } },
          variant_options_1_in_stock: { repeated: { values: ['Default Title'] } },
          variant_options_2: { repeated: { values: [''] } },
          variant_options_2_in_stock: { repeated: { values: [''] } },
          variant_options_3: { repeated: { values: [''] } },
          variant_options_3_in_stock: { repeated: { values: [''] } },
          variant_positions: { repeated: { values: ['1'] } },
          variant_prices: { repeated: { values: ['27058.15'] } },
          variant_quantities: { repeated: { values: ['1'] } },
          variant_skus: { repeated: { values: ['GLA968369624'] } },
          variant_tax_codes: { repeated: { values: [''] } },
          variant_titles: { repeated: { values: ['Default Title'] } },
          variant_titles_in_stock: { repeated: { values: ['Default Title'] } },
          variant_weights: { repeated: { values: ['5'] } },
          vendor: { single: 'Glashütte Original' },
        },
        score: 1,
        indexScore: 1,
        relevanceScore: 0.09112235761549395,
      },
    ],
    featureScoreWeight: 0.2,
  },
  queryId: 'c0ef8e5d-eaef-4561-b6e1-113ddd8df87c',
};
