name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: github.repository == 'sajari/sdk-react'

    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # This makes action fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          persist-credentials: false

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          version: 12.x

      - name: Enable corepack
        run: |
          corepack enable
          yarn --version

      - name: Get yarn cache
        id: yarn-cache
        run: 'echo "::set-output name=dir::$(yarn config get cacheFolder)"'

      - uses: actions/cache@v1
        with:
          path: '${{ steps.yarn-cache.outputs.dir }}'
          key: "${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}"
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          yarn
          yarn build

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: yarn release
          title: Release latest to Production
        env:
          GITHUB_TOKEN: ${{ secrets.SAJARI_CI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
