name: Run test on open PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOT_NAME: 'github-actions[bot]'
      BOT_TYPE: Bot
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Enable corepack
        run: |
          corepack enable
          yarn --version

      - name: Get yarn cache
        id: yarn-cache
        run: 'echo "::set-output name=dir::$(yarn config get cacheFolder)"'

      - uses: actions/cache@v1
        with:
          path: '${{ steps.yarn-cache.outputs.dir }}'
          key: "${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}"
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependency and run test
        run: |
          yarn
          yarn test:ci
